-- StepWithNani all-in-one schema and migrations
-- Generated by merging repo SQL files in a safe execution order.

-- ====================================================================
-- Source: db_schema.sql
-- ====================================================================
-- StepWithNani core schema (ordered for FKs, no custom types)

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- Profiles
create table if not exists profiles (
  id uuid primary key default uuid_generate_v4(),
  auth_user_id uuid references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  phone text,
  avatar_url text,
  role text not null default 'student', -- student|teacher|admin
  core_subject text,
  education_level text, -- B.Tech|12th|Intermediate|10th
  study_stream text, -- Computer Science|Mechanical|MPC|BIPC|MBPC for branches/streams
  diploma_certificate text, -- For 12th grade students - diploma/certificate details
  premium_until timestamptz,
  assigned_teacher_id uuid references profiles(id),
  is_locked boolean default false,
  locked_until timestamptz,
  is_disabled boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Courses
create table if not exists courses (
  id bigserial primary key,
  title text not null,
  description text,
  category text not null,
  thumbnail_url text,
  video_url text,
  notes_url text,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists course_topics (
  id bigserial primary key,
  course_id bigint references courses(id) on delete cascade,
  title text not null,
  order_index int default 0
);

create table if not exists course_notes (
  id bigserial primary key,
  course_id bigint references courses(id) on delete cascade,
  topic_id bigint references course_topics(id) on delete set null,
  content text,
  order_index int default 0
);

-- Enrollments and progress
create table if not exists enrollments (
  id bigserial primary key,
  student_id uuid references profiles(id) on delete cascade,
  course_id bigint references courses(id) on delete cascade,
  progress numeric default 0,
  exam_score numeric,
  completed boolean default false,
  certificate_id uuid,
  enrolled_at timestamptz default now(),
  unique (student_id, course_id)
);

-- Payments and premium grants
create table if not exists payments (
  id bigserial primary key,
  user_id uuid references profiles(id) on delete cascade,
  amount numeric not null,
  currency text default 'INR',
  status text not null,
  valid_until timestamptz,
  gateway_ref text,
  created_at timestamptz default now()
);

create table if not exists premium_grants (
  id bigserial primary key,
  user_id uuid references profiles(id) on delete cascade,
  granted_by uuid references profiles(id),
  reason text,
  valid_until timestamptz,
  revoked_at timestamptz,
  created_at timestamptz default now()
);

-- Exams
create table if not exists exams (
  id bigserial primary key,
  course_id bigint references courses(id) on delete cascade,
  duration_minutes int default 100,
  pass_percent int default 70,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists exam_questions (
  id bigserial primary key,
  exam_id bigint references exams(id) on delete cascade,
  question text not null,
  options text[] not null,
  correct_index int not null,
  order_index int default 0
);

create table if not exists exam_submissions (
  id bigserial primary key,
  exam_id bigint references exams(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  score_percent numeric,
  passed boolean,
  started_at timestamptz default now(),
  submitted_at timestamptz,
  proctor_flags jsonb default '{}'::jsonb,
  attempt_number int default 1,
  next_attempt_allowed_at timestamptz,
  unique (exam_id, user_id)
);

-- Admin overrides for retake windows
create table if not exists exam_retake_overrides (
  id bigserial primary key,
  user_id uuid references profiles(id) on delete cascade,
  course_id bigint references courses(id) on delete cascade,
  allow_retake_at timestamptz,
  created_at timestamptz default now()
);

-- Global exam settings (single-row, default lock days)
create table if not exists exam_settings (
  id int primary key default 1,
  default_lock_days int default 60
);

insert into exam_settings (id, default_lock_days)
  values (1, 60)
  on conflict (id) do nothing;

-- Certificates and verification
create table if not exists certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade,
  course_id bigint references courses(id) on delete cascade,
  exam_submission_id bigint references exam_submissions(id),
  issued_at timestamptz default now(),
  pdf_url text,
  revoked_at timestamptz
);

create table if not exists certificate_verifications (
  id bigserial primary key,
  certificate_id uuid references certificates(id) on delete cascade,
  verified_at timestamptz default now(),
  requester_ip inet
);

-- Career guidance
create table if not exists guidance_requests (
  id bigserial primary key,
  student_id uuid references profiles(id) on delete cascade,
  topic text,
  notes text,
  status text default 'pending', -- pending|assigned|scheduled|completed
  assigned_to_teacher_id uuid references profiles(id),
  created_at timestamptz default now(),
  assigned_at timestamptz
);

create table if not exists guidance_sessions (
  id bigserial primary key,
  request_id bigint references guidance_requests(id) on delete cascade,
  teacher_id uuid references profiles(id),
  scheduled_for timestamptz,
  join_link text,
  status text default 'scheduled', -- scheduled|completed
  reminder_sent_at timestamptz,
  created_at timestamptz default now()
);

-- Teacher assignments
create table if not exists teacher_assignments (
  id bigserial primary key,
  teacher_id uuid references profiles(id),
  student_id uuid references profiles(id),
  assigned_by uuid references profiles(id),
  assigned_at timestamptz default now(),
  active boolean default true,
  unique (teacher_id, student_id)
);

-- Live classes and attendance
create table if not exists class_sessions (
  id bigserial primary key,
  teacher_id uuid references profiles(id),
  title text,
  scheduled_for timestamptz,
  duration_minutes int default 60,
  join_link text,
  created_by uuid references profiles(id),
  created_at timestamptz default now()
);

-- Leaves with comments and revoke
create table if not exists teacher_leaves (
  id bigserial primary key,
  teacher_id uuid references profiles(id),
  start_date date,
  end_date date,
  reason text,
  status text default 'pending',
  admin_comments text,
  decided_by uuid references profiles(id),
  decided_at timestamptz,
  created_at timestamptz default now()
);

-- Compatibility view for legacy clients querying leave_requests
create or replace view leave_requests as
select
  id,
  teacher_id,
  start_date,
  end_date,
  reason,
  status,
  admin_comments,
  decided_by,
  decided_at,
  created_at
from teacher_leaves;

-- Session reassignments (when teacher is on leave)
create table if not exists session_reassignments (
  id bigserial primary key,
  session_id bigint references class_sessions(id) on delete cascade,
  original_teacher_id uuid references profiles(id),
  reassigned_to_teacher_id uuid references profiles(id),
  leave_id bigint references teacher_leaves(id),
  reason text,
  reassigned_at timestamptz default now(),
  reverted_at timestamptz
);

create table if not exists class_attendance (
  id bigserial primary key,
  session_id bigint references class_sessions(id) on delete cascade,
  student_id uuid references profiles(id),
  teacher_id uuid references profiles(id),
  attended boolean,
  marked_at timestamptz default now(),
  unique (session_id, student_id)
);

-- Guidance attendance (separate from class attendance)
create table if not exists guidance_attendance (
  id bigserial primary key,
  session_id bigint references guidance_sessions(id) on delete cascade,
  student_id uuid references profiles(id),
  teacher_id uuid references profiles(id),
  attended boolean,
  marked_at timestamptz default now(),
  unique (session_id, student_id)
);

-- Chat (admin visible)
create table if not exists chat_groups (
  id bigserial primary key,
  name text,
  group_type text default 'student_teacher', -- student_teacher|group
  created_by uuid references profiles(id),
  created_at timestamptz default now(),
  is_admin_managed boolean default true
);

create table if not exists chat_members (
  id bigserial primary key,
  group_id bigint references chat_groups(id) on delete cascade,
  user_id uuid references profiles(id),
  role text default 'member',
  unique (group_id, user_id)
);

create table if not exists chat_messages (
  id bigserial primary key,
  group_id bigint references chat_groups(id) on delete cascade,
  sender_id uuid references profiles(id),
  content text,
  created_at timestamptz default now()
);

-- Admin-only requests before teacher assignment
create table if not exists admin_requests (
  id bigserial primary key,
  user_id uuid references profiles(id),
  type text,
  content text,
  status text default 'open',
  created_at timestamptz default now()
);

-- Renewal reminders
create table if not exists renewal_reminders (
  id bigserial primary key,
  user_id uuid references profiles(id),
  reminder_for timestamptz,
  sent_at timestamptz
);

-- Admin notifications
create table if not exists admin_notifications (
  id bigserial primary key,
  admin_id uuid references profiles(id),
  title text not null,
  content text not null,
  type text default 'info', -- info|warning|success
  target_role text default 'all', -- all|student|teacher
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists notification_reads (
  id bigserial primary key,
  notification_id bigint references admin_notifications(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  read_at timestamptz default now(),
  unique (notification_id, user_id)
);

-- Seed courses
insert into courses (title, category, description) values
  ('C Programming Fundamentals', 'Programming', 'Master the basics of C programming language'),
  ('Advanced Java Programming', 'Programming', 'Deep dive into Java enterprise development'),
  ('Python Data Science', 'Data Science', 'Learn data analysis and machine learning with Python'),
  ('JavaScript ES6+', 'Programming', 'Modern JavaScript features and best practices'),
  ('React JS Full Stack', 'Web Development', 'Build modern web apps with React'),
  ('Node.js Backend', 'Web Development', 'Server-side JavaScript with Node and Express'),
  ('Operating Systems Internals', 'Core CS', 'OS concepts, scheduling, memory management'),
  ('Database Management (DBMS)', 'Core CS', 'Relational databases, SQL, normalization'),
  ('Data Structures & Algorithms', 'Core CS', 'Essential DSA for coding interviews'),
  ('Computer Networks', 'Core CS', 'TCP/IP, protocols, network security'),
  ('R for Statistics', 'Data Science', 'Statistical computing and graphics with R'),
  ('Machine Learning Basics', 'Data Science', 'Intro to ML algorithms and models'),
  ('Deep Learning with TensorFlow', 'Data Science', 'Neural networks and deep learning'),
  ('SQL Mastery', 'Database', 'Advanced SQL queries and optimization'),
  ('MongoDB Essentials', 'Database', 'NoSQL database design and operations'),
  ('PostgreSQL Deep Dive', 'Database', 'Advanced PostgreSQL features'),
  ('Redis Caching', 'Database', 'In-memory data structure store'),
  ('Docker Containers', 'DevOps', 'Containerization with Docker'),
  ('Kubernetes Orchestration', 'DevOps', 'Container orchestration at scale'),
  ('CI/CD Pipelines', 'DevOps', 'Continuous integration and deployment'),
  ('Linux System Admin', 'DevOps', 'Linux server management'),
  ('Git Version Control', 'Tools', 'Master Git workflows and collaboration'),
  ('AWS Cloud Practitioner', 'Cloud', 'Amazon Web Services fundamentals'),
  ('Azure Fundamentals', 'Cloud', 'Microsoft Azure cloud platform'),
  ('Google Cloud Platform', 'Cloud', 'GCP services and architecture'),
  ('System Design Fundamentals', 'Core CS', 'Scalable system architecture'),
  ('Microservices Architecture', 'Web Development', 'Building distributed systems'),
  ('GraphQL API Design', 'Web Development', 'Modern API development'),
  ('TypeScript Essentials', 'Programming', 'Type-safe JavaScript development'),
  ('Go Programming', 'Programming', 'Golang for backend development'),
  ('Rust Programming', 'Programming', 'Systems programming with Rust'),
  ('Swift iOS Development', 'Mobile', 'Build iOS apps with Swift'),
  ('Kotlin Android Development', 'Mobile', 'Android app development'),
  ('Flutter Cross-Platform', 'Mobile', 'Build apps for iOS and Android'),
  ('React Native', 'Mobile', 'JavaScript mobile development'),
  ('Cybersecurity Basics', 'Security', 'Introduction to information security'),
  ('Ethical Hacking', 'Security', 'Penetration testing fundamentals'),
  ('Web Security', 'Security', 'Secure web application development'),
  ('Cryptography Fundamentals', 'Security', 'Encryption and secure communication'),
  ('Blockchain Basics', 'Emerging Tech', 'Distributed ledger technology'),
  ('Smart Contract Development', 'Emerging Tech', 'Ethereum and Solidity'),
  ('AI & Machine Learning', 'AI', 'Artificial intelligence fundamentals'),
  ('Natural Language Processing', 'AI', 'Text processing and understanding'),
  ('Computer Vision', 'AI', 'Image processing and recognition'),
  ('UI/UX Design Principles', 'Design', 'User interface and experience design'),
  ('Figma for Developers', 'Design', 'Design tool for product teams'),
  ('Tailwind CSS', 'Web Development', 'Utility-first CSS framework'),
  ('Bootstrap 5', 'Web Development', 'Responsive web design framework'),
  ('Vue.js Framework', 'Web Development', 'Progressive JavaScript framework'),
  ('Angular Framework', 'Web Development', 'Enterprise web applications'),
  ('Django Web Framework', 'Web Development', 'Python web development'),
  ('Ruby on Rails', 'Web Development', 'Full-stack web development'),
  ('PHP Laravel', 'Web Development', 'Modern PHP framework')
  on conflict do nothing;

-- RLS Policies for Chat Tables
ALTER TABLE chat_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- Chat groups: users can see groups they're members of
DROP POLICY IF EXISTS "users_select_own_chat_groups" ON chat_groups;
CREATE POLICY "users_select_own_chat_groups" ON chat_groups
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM chat_members 
      WHERE chat_members.group_id = chat_groups.id 
      AND chat_members.user_id = auth.uid()
    )
  );

-- Chat members: users can see members of their groups
DROP POLICY IF EXISTS "users_select_chat_members" ON chat_members;
CREATE POLICY "users_select_chat_members" ON chat_members
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM chat_members AS cm
      WHERE cm.group_id = chat_members.group_id 
      AND cm.user_id = auth.uid()
    )
  );

-- Chat members: insert own membership
DROP POLICY IF EXISTS "users_insert_chat_members" ON chat_members;
CREATE POLICY "users_insert_chat_members" ON chat_members
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() OR 
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Chat messages: users can see messages from their groups
DROP POLICY IF EXISTS "users_select_chat_messages" ON chat_messages;
CREATE POLICY "users_select_chat_messages" ON chat_messages
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM chat_members 
      WHERE chat_members.group_id = chat_messages.group_id 
      AND chat_members.user_id = auth.uid()
    )
  );

-- Chat messages: users can send messages to their groups
DROP POLICY IF EXISTS "users_insert_chat_messages" ON chat_messages;
CREATE POLICY "users_insert_chat_messages" ON chat_messages
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = auth.uid() AND
    EXISTS (
      SELECT 1 FROM chat_members 
      WHERE chat_members.group_id = chat_messages.group_id 
      AND chat_members.user_id = auth.uid()
    )
  );

-- ====================================================================
-- Source: migration_add_course_columns.sql
-- ====================================================================
-- Add missing columns to courses table
-- This migration adds support for notes URLs and ensures all course fields exist

ALTER TABLE courses ADD COLUMN IF NOT EXISTS notes_url TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

-- Add description if missing
ALTER TABLE courses ADD COLUMN IF NOT EXISTS description TEXT;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE INDEX IF NOT EXISTS idx_courses_is_active ON courses(is_active);

-- ====================================================================
-- Source: add_image_url_column.sql
-- ====================================================================
-- Add image_url column to courses table
-- This allows admins to add course images in addition to thumbnails

ALTER TABLE courses ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Optional: You can also rename thumbnail_url to image_url if you want consistency
-- ALTER TABLE courses RENAME COLUMN thumbnail_url TO image_url;

-- Update existing records to use thumbnail_url as image_url if needed
-- UPDATE courses SET image_url = thumbnail_url WHERE image_url IS NULL AND thumbnail_url IS NOT NULL;

-- ====================================================================
-- Source: add_is_disabled.sql
-- ====================================================================
-- Migration: Add is_disabled column to profiles table
-- Purpose: Enable admin to temporarily disable user accounts without deletion

ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS is_disabled boolean default false;

-- Add comment
COMMENT ON COLUMN profiles.is_disabled IS 'When true, user cannot login. Can be re-enabled by admin.';

-- ====================================================================
-- Source: add_locked_until.sql
-- ====================================================================
-- Migration: Add locked_until column to profiles table
-- Run this in Supabase SQL Editor if the column doesn't exist

ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS locked_until timestamptz;

-- This allows tracking when a 60-day lock expires
-- When a user violates exam proctoring, is_locked=true and locked_until=now()+60 days
-- Users are automatically unlocked when locked_until date passes

-- ====================================================================
-- Source: migration_guidance_attendance.sql
-- ====================================================================
-- Migration: Add guidance_attendance table
-- Run this in your Supabase SQL Editor

-- Create guidance_attendance table for guidance session attendance tracking
create table if not exists guidance_attendance (
  id bigserial primary key,
  session_id bigint references guidance_sessions(id) on delete cascade,
  student_id uuid references profiles(id),
  teacher_id uuid references profiles(id),
  attended boolean,
  is_locked boolean default false,
  locked_by uuid references profiles(id),
  marked_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (session_id, student_id)
);

-- Create index for faster queries
create index if not exists idx_guidance_attendance_student on guidance_attendance(student_id);
create index if not exists idx_guidance_attendance_teacher on guidance_attendance(teacher_id);
create index if not exists idx_guidance_attendance_session on guidance_attendance(session_id);

-- Enable Row Level Security
alter table guidance_attendance enable row level security;

-- RLS Policies
create policy "Teachers can view their own guidance attendance"
  on guidance_attendance for select
  using (auth.uid() in (
    select id from profiles where role = 'teacher' and id = teacher_id
  ));

create policy "Students can view their own attendance"
  on guidance_attendance for select
  using (auth.uid() = student_id);

create policy "Teachers can insert/update attendance for their sessions"
  on guidance_attendance for all
  using (auth.uid() in (
    select id from profiles where role = 'teacher' and id = teacher_id
  ));

create policy "Admins can view all guidance attendance"
  on guidance_attendance for select
  using (auth.uid() in (
    select id from profiles where role = 'admin'
  ));

-- ====================================================================
-- Source: migration_jitsi_meetings.sql
-- ====================================================================
-- Add columns for Jitsi meeting integration to class_sessions table

-- Add meeting_type column (jitsi or external)
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'class_sessions' AND column_name = 'meeting_type'
  ) THEN
    ALTER TABLE class_sessions ADD COLUMN meeting_type VARCHAR(20) DEFAULT 'jitsi';
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'class_sessions' AND column_name = 'meeting_link'
  ) THEN
    ALTER TABLE class_sessions ADD COLUMN meeting_link TEXT;
  END IF;
END $$;

-- Create class_session_participants table for tracking who can join
CREATE TABLE IF NOT EXISTS class_session_participants (
  id BIGSERIAL PRIMARY KEY,
  session_id BIGINT REFERENCES class_sessions(id) ON DELETE CASCADE,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(session_id, student_id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_session_participants_session ON class_session_participants(session_id);
CREATE INDEX IF NOT EXISTS idx_session_participants_student ON class_session_participants(student_id);

-- Enable RLS
ALTER TABLE class_session_participants ENABLE ROW LEVEL SECURITY;

-- RLS Policies for participants
DROP POLICY IF EXISTS "participants_select_policy" ON class_session_participants;
CREATE POLICY "participants_select_policy"
  ON class_session_participants FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    ) OR
    auth.uid() = student_id
  );

DROP POLICY IF EXISTS "participants_insert_policy" ON class_session_participants;
CREATE POLICY "participants_insert_policy"
  ON class_session_participants FOR INSERT
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    )
  );

DROP POLICY IF EXISTS "participants_delete_policy" ON class_session_participants;
CREATE POLICY "participants_delete_policy"
  ON class_session_participants FOR DELETE
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    )
  );

-- Update existing records to have meeting_type
UPDATE class_sessions 
SET meeting_type = CASE 
  WHEN join_link IS NOT NULL THEN 'external'
  ELSE 'jitsi'
END
WHERE meeting_type IS NULL;

-- Rename scheduled_at to scheduled_for for consistency (if column exists)
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'class_sessions' AND column_name = 'scheduled_at'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'class_sessions' AND column_name = 'scheduled_for'
  ) THEN
    ALTER TABLE class_sessions RENAME COLUMN scheduled_at TO scheduled_for;
  END IF;
END $$;

-- Drop existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "class_sessions_jitsi_select_policy" ON class_sessions;
DROP POLICY IF EXISTS "class_sessions_jitsi_insert_policy" ON class_sessions;
DROP POLICY IF EXISTS "class_sessions_jitsi_update_policy" ON class_sessions;

-- Enable RLS if not already enabled
ALTER TABLE class_sessions ENABLE ROW LEVEL SECURITY;

-- Create new policies with unique names
CREATE POLICY "class_sessions_jitsi_select_policy"
  ON class_sessions FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    ) OR
    auth.uid() IN (
      SELECT student_id FROM class_session_participants WHERE session_id = class_sessions.id
    ) OR
    NOT EXISTS (
      SELECT 1 FROM class_session_participants WHERE session_id = class_sessions.id
    )
  );

CREATE POLICY "class_sessions_jitsi_insert_policy"
  ON class_sessions FOR INSERT
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    )
  );

CREATE POLICY "class_sessions_jitsi_update_policy"
  ON class_sessions FOR UPDATE
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    )
  );

-- Add DELETE policy for class_sessions
DROP POLICY IF EXISTS "class_sessions_jitsi_delete_policy" ON class_sessions;
CREATE POLICY "class_sessions_jitsi_delete_policy"
  ON class_sessions FOR DELETE
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role IN ('admin', 'teacher')
    )
  );

-- Add comments
COMMENT ON COLUMN class_sessions.meeting_type IS 'Type of meeting platform: jitsi (our platform) or external (zoom, meet, etc)';
COMMENT ON COLUMN class_sessions.meeting_link IS 'External meeting link if meeting_type is external';
COMMENT ON TABLE class_session_participants IS 'Students invited to specific class sessions. If empty, all students can join';

-- ====================================================================
-- Source: migration_notifications_fix.sql
-- ====================================================================
-- Fix notifications system by creating tables and adding RLS policies

-- Create admin_notifications table if it doesn't exist
CREATE TABLE IF NOT EXISTS admin_notifications (
  id BIGSERIAL PRIMARY KEY,
  admin_id UUID REFERENCES profiles(id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type TEXT DEFAULT 'info', -- info|warning|success
  target_role TEXT DEFAULT 'all', -- all|student|teacher
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add target_role column if it doesn't exist (for existing tables)
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'admin_notifications' AND column_name = 'target_role'
  ) THEN
    ALTER TABLE admin_notifications ADD COLUMN target_role TEXT DEFAULT 'all';
  END IF;
END $$;

-- Create notification_reads table if it doesn't exist
CREATE TABLE IF NOT EXISTS notification_reads (
  id BIGSERIAL PRIMARY KEY,
  notification_id BIGINT REFERENCES admin_notifications(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (notification_id, user_id)
);

-- Enable RLS on both tables
ALTER TABLE admin_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_reads ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "admin_notifications_select_policy" ON admin_notifications;
DROP POLICY IF EXISTS "admin_notifications_insert_policy" ON admin_notifications;
DROP POLICY IF EXISTS "admin_notifications_update_policy" ON admin_notifications;
DROP POLICY IF EXISTS "admin_notifications_delete_policy" ON admin_notifications;
DROP POLICY IF EXISTS "notification_reads_select_policy" ON notification_reads;
DROP POLICY IF EXISTS "notification_reads_insert_policy" ON notification_reads;
DROP POLICY IF EXISTS "notification_reads_delete_policy" ON notification_reads;

-- Admin Notifications Policies
-- Anyone can read notifications targeted to their role or 'all'
CREATE POLICY "admin_notifications_select_policy"
  ON admin_notifications FOR SELECT
  USING (
    target_role = 'all' OR
    target_role = (SELECT role FROM profiles WHERE id = auth.uid())
  );

-- Only admins can create notifications
CREATE POLICY "admin_notifications_insert_policy"
  ON admin_notifications FOR INSERT
  WITH CHECK (
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
  );

-- Only admins can update their own notifications
CREATE POLICY "admin_notifications_update_policy"
  ON admin_notifications FOR UPDATE
  USING (
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
  );

-- Only admins can delete notifications
CREATE POLICY "admin_notifications_delete_policy"
  ON admin_notifications FOR DELETE
  USING (
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
  );

-- Notification Reads Policies
-- Users can see their own read records
CREATE POLICY "notification_reads_select_policy"
  ON notification_reads FOR SELECT
  USING (user_id = auth.uid());

-- Users can mark notifications as read
CREATE POLICY "notification_reads_insert_policy"
  ON notification_reads FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Users can delete their own read records
CREATE POLICY "notification_reads_delete_policy"
  ON notification_reads FOR DELETE
  USING (user_id = auth.uid());

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_admin_notifications_target_role ON admin_notifications(target_role);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_created_at ON admin_notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_reads_user_id ON notification_reads(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_reads_notification_id ON notification_reads(notification_id);

-- Add comments
COMMENT ON TABLE admin_notifications IS 'System-wide notifications sent by admins to users';
COMMENT ON TABLE notification_reads IS 'Tracks which users have read which notifications';

-- ====================================================================
-- Source: add_admin_rls_policies.sql
-- ====================================================================
-- RLS Policies for Admin Account Management
-- These policies allow admins to manage all user accounts

-- First, ensure RLS is enabled
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Admin policy: Allow admins to view all profiles
CREATE POLICY "Admins can view all profiles"
ON profiles FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
);

-- Admin policy: Allow admins to update all profiles
CREATE POLICY "Admins can update all profiles"
ON profiles FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
);

-- Admin policy: Allow admins to delete profiles
CREATE POLICY "Admins can delete profiles"
ON profiles FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
);

-- User policy: Allow users to view own profile
CREATE POLICY "Users can view own profile"
ON profiles FOR SELECT
USING (auth.uid() = id);

-- User policy: Allow users to update own profile
CREATE POLICY "Users can update own profile"
ON profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Note: We don't allow users to delete their own profile via app
-- Only admins can delete accounts

-- ====================================================================
-- Source: fix_rls_policies.sql
-- ====================================================================
-- FIX: Drop old problematic policies and create simpler ones
-- This fixes the 500 error when fetching profiles

-- Drop old policies if they exist
DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can update all profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can delete profiles" ON profiles;
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Simple policy: Allow all authenticated users to view all profiles
CREATE POLICY "Everyone can view profiles"
ON profiles FOR SELECT
TO authenticated
USING (true);

-- Simple policy: Allow users to update their own profile
CREATE POLICY "Users can update own profile"
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Admin policy: Allow admins to update any profile
CREATE POLICY "Admins can update all profiles"
ON profiles FOR UPDATE
TO authenticated
USING (
  (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
)
WITH CHECK (
  (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
);

-- Admin policy: Allow admins to delete profiles
CREATE POLICY "Admins can delete profiles"
ON profiles FOR DELETE
TO authenticated
USING (
  (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
);

-- ====================================================================
-- Source: simplified_rls_policies.sql
-- ====================================================================
-- Simplified RLS Policies - BEST VERSION
-- Drop all old policies first

DROP POLICY IF EXISTS "Everyone can view profiles" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
DROP POLICY IF EXISTS "Admins can update all profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can delete profiles" ON profiles;
DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- SIMPLE APPROACH: Allow authenticated users to read all profiles
CREATE POLICY "authenticated_select"
ON profiles FOR SELECT
TO authenticated
USING (true);

-- Allow users to update their own profile only
CREATE POLICY "user_update_own"
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Allow users to insert their own profile
DROP POLICY IF EXISTS "user_insert_own" ON profiles;
CREATE POLICY "user_insert_own"
ON profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

-- Allow admins to update any profile
CREATE POLICY "admin_update_all"
ON profiles FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid()
    AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid()
    AND role = 'admin'
  )
);

-- Allow admins to delete any profile
CREATE POLICY "admin_delete_all"
ON profiles FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid()
    AND role = 'admin'
  )
);
