create table if not exists public.multi_session_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  full_name text,
  email text,
  phone text,
  user_role text,
  existing_device_label text,
  new_device_label text,
  existing_updated_at timestamptz,
  violation_count integer not null default 1,
  is_repeat_offense boolean not null default false,
  admin_status text not null default 'new' check (admin_status in ('new', 'reviewed', 'resolved')),
  admin_notes text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists idx_multi_session_alerts_status_created
  on public.multi_session_alerts(admin_status, created_at desc);

alter table if exists public.multi_session_alerts enable row level security;

drop policy if exists "Admins can read multi session alerts" on public.multi_session_alerts;
create policy "Admins can read multi session alerts"
  on public.multi_session_alerts
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  );

drop policy if exists "Users can insert own multi session alerts" on public.multi_session_alerts;
create policy "Users can insert own multi session alerts"
  on public.multi_session_alerts
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Admins can update multi session alerts" on public.multi_session_alerts;
create policy "Admins can update multi session alerts"
  on public.multi_session_alerts
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  );
