-- Premium grant audit trail with reason and person mapping.

create table if not exists public.premium_grants (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  granted_by uuid references public.profiles(id) on delete set null,
  valid_until timestamptz,
  reason text not null
);

alter table public.premium_grants
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists user_id uuid,
  add column if not exists granted_by uuid,
  add column if not exists valid_until timestamptz,
  add column if not exists reason text;

create index if not exists idx_premium_grants_user_created
  on public.premium_grants(user_id, created_at desc);

create index if not exists idx_premium_grants_created
  on public.premium_grants(created_at desc);

alter table public.premium_grants enable row level security;

drop policy if exists "Admins can read premium grants" on public.premium_grants;
create policy "Admins can read premium grants"
on public.premium_grants
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

drop policy if exists "Users can read own premium grants" on public.premium_grants;
create policy "Users can read own premium grants"
on public.premium_grants
for select
to authenticated
using (
  user_id = auth.uid()
);

drop policy if exists "Admins can insert premium grants" on public.premium_grants;
create policy "Admins can insert premium grants"
on public.premium_grants
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
  and granted_by = auth.uid()
);
