-- Admin activity logs for auditing admin navigation and actions.

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  admin_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null default 'navigation',
  action text not null,
  target text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists idx_admin_activity_logs_created_at
  on public.admin_activity_logs(created_at desc);

create index if not exists idx_admin_activity_logs_admin_id
  on public.admin_activity_logs(admin_id, created_at desc);

alter table public.admin_activity_logs enable row level security;

drop policy if exists "Admins can read activity logs" on public.admin_activity_logs;
create policy "Admins can read activity logs"
on public.admin_activity_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

drop policy if exists "Admins can insert activity logs" on public.admin_activity_logs;
create policy "Admins can insert activity logs"
on public.admin_activity_logs
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
  and admin_id = auth.uid()
);
